### PR TITLE
Refactor code, make it more python and squeeze out small performance gains.

### PR DESCRIPTION
**Pull request by Uzaaft**
Original issue was #25.
Scope of this PR:

* Migration to comprehensions
* Move to literals instead of `list()` and `dict()`
* Use if-expressions
* Use `yield from` instead of `yield`

### CODE REVIEW

**Comment by Uzaaft** [comment]
Reason for [eb4cbac](https://github.com/niemasd/TreeSwift/pull/26/commits/eb4cbac8a204d8ba94c7c9574c2206c532f07e28):

Simple microbenchmark, but:

image

**Comment by Uzaaft** [comment]
Microbenchmark for [e287123](https://github.com/niemasd/TreeSwift/pull/26/commits/e287123156459a6324821a5f3d7c7e20754f1ca4):
image

**Comment by Uzaaft** [comment]
@niemasd  Ready for initial review.

I've got additional changes that I want to run by you, for.example the usage of if-expressions:
image

Instead of 
image

There is also a few variable assignments that should be changes. For.example the usage of `all` and `next`, as these are built in variables/functions into python.

**Review by niemasd — APPROVED** [review]
Thank you for the contributions!! I appreciate it! I reverted some changes and made some modifications of my own, and it's ready to integrate!

**Comment by Uzaaft** [comment]
> @niemasd Ready for initial review.
> 
> I've got additional changes that I want to run by you, for.example the usage of if-expressions: image
> 
> Instead of image
> 
> There is also a few variable assignments that should be changes. For.example the usage of `all` and `next`, as these are built in variables/functions into python.

What about the changes proposed here? @niemasd

**Comment by niemasd** [comment]
Ah, sorry, I missed that! Yes, both ideas (1: using if-else variable assignment expressions, and 2: renaming variables whose names conflict with built-in Python variables/functions/keywords) sound great!

**Pull request merged**
