### PR TITLE
Refactor code, make it more python and squeeze out small performance gains

### PR DESCRIPTION
**Pull request by Uzaaft**
Refactor the codes, and make code more pythonic.
Squeeze out performance gains by using literals instead of functions(`{} `instead of `dict()`)
Swap out for loops with comprehensions
Speed up string interpolation by using f-string.

I just wanted your feedback on the changes before I do too much. 
Especially about the lines where you have `;` in the lines, for example: 

```python
....
out = self.string_rep; del self.string_rep
...
```
Where I end up splitting them up into:

```python
...
out = self.string_rep 
del self.string_rep
...
```

### CODE REVIEW

**Comment by niemasd** [comment]
Thanks for the pull request! Regarding your question about lines like the following:

```python
out = self.string_rep; del self.string_rep
```

I typically do this when I'm executing multiple Python statements that are part of a single logical thought (e.g. in this case, the single logical thought is "Move the representative string from an instance variable to a temporary holder variable"). Thus, I would prefer keeping these together so it's visually simpler for me to see that they're closely related (though it would be functionally equivalent to the splitting that you suggest)

Regarding replacing `list()` and `dict()` with literals `[]` and `{}`, I originally used literals in the first versions of TreeSwift, but I switched them to function calls to maintain compatibility with Python 2.6. I recognize that Python 2 has been sunset, and all developers should migrate to Python 3, but I don't want to break compatibility in any legacy Python 2.6 code that depends on TreeSwift. Also, when benchmarking calling `list()`  bunch of times vs. calling `[]` a bunch of times on my laptop (Intel i7 CPU), the runtimes were negligibly close, with `[]` actually being slightly slower in terms of walltime:

```
niema@Niema-Laptop:~$ time (for i in $(seq 1000); do python3 -c "list()" ; done)

real    0m10.028s
user    0m8.479s
sys     0m1.598s
niema@Niema-Laptop:~$ time (for i in $(seq 1000); do python3 -c "[]" ; done)

real    0m10.142s
user    0m8.719s
sys     0m1.501s
```

So I won't be able to accept the `list()` to `[]` and `dict()` to `{}` changes to maintain Python 2.6 compatibility, and I will keep the instances of multiple statements per line as-is, but I'd be happy to accept an updated pull request with just the comprehensions! I'm happy to either let you update your pull request accordingly if you want the commits to show up under your account, or I'm happy to separately pull them out and incorporate them myself and then credit you in the commit description + version update release; whichever you prefer

**Comment by niemasd** [comment]
Ah, actually, this pull request prompted me to dig through the TreeSwift commit history, and I stumbled upon this commit:

https://github.com/niemasd/TreeSwift/commit/ca9a44dd34fe56503c389bdd5432820b44e94c86

So I actually also had originally used comprehensions in the initial versions of TreeSwift, but I switched away from them to maintain Python 2.6 compatibility. However, the speedup of comprehensions vs. general loops is quite significant and would make a non-trivial impact on the algorithms TreeSwift implements

Thus, I'd be open to switching to comprehensions despite the fact that they would break Python 2.6 compatibility, and if TreeSwift will break Python 2.6 compatibility anyways, it might as well switch `list()` to `[]` and `dict()` to `{}` to get those savings as well

So as in my previous comment, please feel free to make those updates to your pull request (i.e., reverting the split commands back into their original single-line form), and I'd be happy to accept the pull request, or I'd also be happy to make those edits manually myself and credit you if it would save you time. Either would be fine with me 😄

**Comment by Uzaaft** [comment]
I'll try and revert the splitted lines in a later commit, after refactoring the control flow to simplify it. I'll ping you whenever the PR is ready to be reviewed 🤓

**Comment by Uzaaft** [comment]
Just for the sake of having it documented in this PR:
An overview of the benchmark provided by you, but both for list() vs [], and dict() vs {}:
image

**Pull request closed without merging**
